title: Leo's site
nav:
  - name: 首页
    link: /
  - name: 关于
    link: /about/
  - name: 文章
    link: /blogs/
other-urls:
  - name: GitHub
    link: https://github.com/Leo-hele/
  - name: Gitee
    link: https://gitee.com/Leo-hele/
  - name: 洛谷
    link: https://www.luogu.com.cn/user/1068806/
baseurl: ""
url: ""
usersNum: 1
users:
  - name: Leo
    url: https://leo-hele.github.io/
    password: noPassword
