title: Leo's site
favicon: https://gitee.com/Leo-hele/leo-hele.github.io-images/raw/main/favicon.ico
nav:
  - name: 首页
    link: /
  - name: 关于
    link: /about/
  - name: 文章
    link: /blogs/
other-urls:
  - name: GitHub
    link: https://github.com/Leo-hele/
  - name: Gitee
    link: https://gitee.com/Leo-hele/
  - namme: Gitcode
    link: https://gitcode.com/Leo-hele/
  - name: 洛谷
    link: https://www.luogu.com.cn/user/1068806
imgs:
    - name: search
      link: https://gitee.com/Leo-hele/leo-hele.github.io-images/raw/main/search.png
baseurl: ""
url: "localhost:4000"
usersNum: 1
users:
  - name: Leo-hele
    password: noPassword
    image: https://gitee.com/Leo-hele/leo-hele.github.io-images/raw/main/favicon.ico
    email: Leo-hele@outlook.com
collections:
  robots.txt:
    output: true
    permalink: /robots.txt
  com.chrome.devtools.json:
    output: true
gems:
  - jekyll-sitemap
  - liquid
